apiVersion: v1
kind: Service
metadata:
  name: enterprise-devops-service
  namespace: enterprise-platform

spec:
  type: NodePort

  selector:
    app: enterprise-devops-app

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080